package home

var phrases = map[string]map[string]string{
	"bg": {
		"head-description": "Заивод Логистикс, вашия доверен партньор в международния транспорт.",
		"title": "Заивод Логистикс",
		"hero-title": "Глобални Логистични Решения, Които Задвижват Вашия Успех",
		"hero-description": "Вашият доверен партньор в международния транспорт и търговия с автомобили. Доставяме превъзходство на всички континенти от 2010 г.",
		"hero-button-get-started": "Започнете",
		"hero-button-our-services": "Нашите Услуги",
		
		"about-title": "Вашият партньор в глобалната търговия",
		"about-description": "Zaivod Logistics е транспортна компания, която се специализира в превоза на широк спектър от стоки из целия ЕС и Азия. С нашата обширна мрежа и експертни знания, ние предлагаме надежни, гъвкави и икономически ефективни решения, които помагат на нашите клиенти да постигнат целите си и да развиват бизнеса си.",
		"find-title": "Къде можете да ни намерите?",
		"find-description": "Намираме се в красивото село Воиводиново. Тук можете да намерите нашата база.",
		"services-title": "Какво предлагаме",
		"services-description": "В Zaivod Logistics ние предлагаме целостни решения за всички ваши логистични потребности. Нашите услуги включват надежния превоз на стоки, гарантирайки, че вашите продукти достигнат до целта им безопасно и навремено. Освен това, ние се специализирани в търговията с автомобили, предлагайки голям набор от опции за тези, които търсят да купят или продадат автомобили. Независимо дали сте бизнес, който търси да превозва стоки, или физическо лице, което търси нов автомобил, ние ви покриваме.",
		"services-transport-title": "Транспортиране на стоки",
		"services-transport-description": "Доставяйки стоките из целия ЕС и Азия безопасно с нашите услуги.",
		"services-cars-title": "Автомобилни търговия",
		"services-cars-description": "Купете качествени камиони и коли от нас.",
		"contacts-title": "Свържете се с нас",
		"contacts-description": "Ние бихме искали да отговорим на всички въпроси, свързани с нашата бъдеща работа заедно. Можете да ни пишете на <b>zaidsadeqhi@gmail.com</b> или да използвате формата по-долу.",
		"contacts-company": "Име на компания",
		"contacts-first-name": "Име",
		"contacts-last-name": "Фамилия",
		"contacts-email": "Имейл",
		"contacts-phone": "Телефон",
		"contacts-message": "Съобщение",
		"contacts-submit": "Изпрати",
	},
	"en": {
		"head-description": "Zaivod Logistics, your trusted parthner in international trade.",
		"title": "Zaivod Logistics",
		"hero-title": "Global Logistics Solutions That Drive Your Success",
		"hero-description": "Your trusted partner in international transportation and vehicle trading. Delivering excellence across continents since 2010.",
		"hero-button-get-started": "Get Started",
		"hero-button-our-services": "Our Services",
		
		"about-title": "Your Partner in Global Trade",
		"about-description": "Zaivod Logistics is a transport company specializing in the transportation of a wide range of goods throughout the EU and Asia. With our extensive network and expert knowledge, we offer reliable, flexible, and cost-effective solutions that help our customers achieve their goals and grow their business.",
		"find-title": "Where can you find us?",
		"find-description": "We are located in the beautiful village of Voevodinovo. Here you can find our base.",
		"services-title": "What We Offer",
		"services-description": "At Zaivod Logistics, we offer comprehensive solutions for all your logistics needs. Our services include reliable cargo transport, ensuring your products reach their destination safely and on time. Additionally, we specialize in car trading, offering a wide range of options for those looking to buy or sell vehicles. Whether you're a business looking to transport goods or an individual looking for a new car, we've got you covered.",
		"services-transport-title": "Cargo Transport",
		"services-transport-description": "Delivering goods throughout the EU and Asia safely with our services.",
		"services-cars-title": "Car Trading",
		"services-cars-description": "Buy quality trucks and cars from us.",
		"contacts-title": "Contact Us",
		"contacts-description": "We would like to answer all questions related to our future work together. You can write to us at <b>zaidsadeqhi@gmail.com</b> or use the form below.",
		"contacts-company": "Company Name",
		"contacts-first-name": "First Name",
		"contacts-last-name": "Last Name",
		"contacts-email": "Email",
		"contacts-phone": "Phone",
		"contacts-message": "Message",
		"contacts-submit": "Send",
	},
	"ps": {
		"head-description": "زود لوژستیک، په نړیواله سوداګرۍ کې ستاسو باوري ملګری.",
		"title": "زېووډ لوژستیکس",
		"hero-title": "نړیوالې لوژستیکي حل چې ستاسې بریالی کوي",
		"hero-description": "ستاسې په نړیوال ګرځیدلو او د موټرو په سوداګرۍ کې د باور وړ شریک. له ۲۰۱۰ څخه راپدېخوا په ټولو لویو وچو کې غوره والی رسول.",
		"hero-button-get-started": "پیل کړئ",
		"hero-button-our-services": "زموږ خدمتونه",
		
		"about-title": "ستاسو شریک په نړیواله سوداګرۍ کې",
		"about-description": "زېووډ لوژستیکس یوه د بار لېږд شرکت دی چې په اروپايي اتحادیه او آسیا کې د مختلفو توکو د لېږد تخصص لري. زموږ د پراخې شبکې او مسلکي پوهې سره، موږ د باور وړ، انعطاف وړ او اقتصادي حل لارې وړاندې کوو چې زموږ پیرودونکو ته مرسته کوي خپل هدفونه ترلاسه کړي او خپل سوداګرۍ وده کړي.",
		"find-title": "چېرې موږ پیدا کولی شئ؟",
		"find-description": "موږ د وووډینوو په ښایسته کلی کې موقعیت لرو. دلته تاسو کولی شئ زموږ اډه ومومئ.",
		"services-title": "هغه څه چې موږ иړاندې کوو",
		"services-description": "په زېووډ لوژستیکس کې، موږ د ستاسو د ټولو لوژستیکي اړتیاو لپاره بشپړې حل لارې وړاندې کوو. زموږ خدمتونه کې د باور وړ د بار لېږد شامل دی، ډاډ ترلاسه کوي چې ستاسو توکي خوندي او په وخت خپلې منزلې ته رسيږي. په دې سربېره، موږ په موټرو په سوداګرۍ کې تخصص لرو، د هغو کسانو لپاره د اختیارونو پراخه لړۍ وړاندې کوو چې غواړي موټرې وپیروي یا وپلوري. که تاسو یو سوداګریز مؤسسه یاست چې بار لېږدوي یا یو څوک یاست چې نوی موټر لټوي، موږ ستاسو د خدمت لپاره حاضر یو.",
		"services-transport-title": "د بار لېږд",
		"services-transport-description": "د اروپايي اتحادې او آسیا په ټولو برخو کې د توکو خوندي لېږد زموږ د خدمتونو سره.",
		"services-cars-title": "د موټرو سوداګري",
		"services-cars-description": "زموږ څخه کیفیتي ټرالرې او موټرې واخلئ.",
		"contacts-title": "موږ سره اړیکه ونیسئ",
		"contacts-description": "موږ غواړو د زموږ د راتلونکي کار یوځای په اړه ټولې پوښتنې ته ځواب ووایو. تاسو کولی شئ زموږ ته په <b>zaidsadeqhi@gmail.com</b> برېښنالیک ولیکئ یا لاندې فورم وکاروئ.",
		"contacts-company": "د شرکت نوم",
		"contacts-first-name": "لومړی نوم",
		"contacts-last-name": "وروستی نوم",
		"contacts-email": "برېښنالیک",
		"contacts-phone": "تلیفون",
		"contacts-message": "پیغام",
		"contacts-submit": "ولېږئ",
	},
}
