package home
var phrases = map[string]map[string]string{
	"bg": {
		"head-description": "Заивод Логистикс, вашия доверен партньор в международния транспорт.",
		"title": "Заивод Логистикс",
		"hero-title": "Глобални Логистични Решения, Които Задвижват Вашия Успех",
		"hero-description": "Вашият доверен партньор в международния транспорт и търговия с автомобили. Доставяме превъзходство на всички континенти от 2010 г.",
		"hero-button-get-started": "Започнете",
		"hero-button-our-services": "Нашите Услуги",
		
		"about-title": "Вашият партньор в глобалната търговия",
		"about-description": "Zaivod Logistics е транспортна компания, която се специализира в превоза на широк спектър от стоки из целия ЕС и Азия. С нашата обширна мрежа и експертни знания, ние предлагаме надежни, гъвкави и икономически ефективни решения, които помагат на нашите клиенти да постигнат целите си и да развиват бизнеса си.",
		"find-title": "Къде можете да ни намерите?",
		"find-description": "Намираме се в красивото село Воиводиново. Тук можете да намерите нашата база.",
		"services-title": "Нашите Услуги",
		"services-subtitle": "Изчерпателни логистични решения за вашите бизнес нужди",
		"services-transport-title": "Транспорт на товари",
		"services-transport-description": "Надежден транспорт на стоки в ЕС и Азия с проследяване в реално време и сигурна доставка.",
		"services-cars-title": "Търговия с автомобили",
		"services-cars-description": "Качествени камиони и коли за продажба с пълна документация и международна доставка.",
		"services-contact-us": "Свържете се с нас",
		"contacts-title": "Свържете се с нас",
		"contacts-description": "Ние бихме искали да отговорим на всички въпроси, свързани с нашата бъдеща работа заедно. Можете да ни пишете на <b>zaidsadeqhi@gmail.com</b> или да използвате формата по-долу.",
		"contacts-company": "Име на компания",
		"contacts-first-name": "Име",
		"contacts-last-name": "Фамилия",
		"contacts-email": "Имейл",
		"contacts-phone": "Телефон",
		"contacts-message": "Съобщение",
		"contacts-submit": "Изпрати",
		"stats-years-experience": "Години Опит",
		"stats-happy-clients": "Доволни Клиенти", 
		"stats-countries-served": "Обслужвани Държави",
		"stats-on-time-delivery": "Навременна Доставка",
	},
	"en": {
		"head-description": "Zaivod Logistics, your trusted parthner in international trade.",
		"title": "Zaivod Logistics",
		"hero-title": "Global Logistics Solutions That Drive Your Success",
		"hero-description": "Your trusted partner in international transportation and vehicle trading. Delivering excellence across continents since 2010.",
		"hero-button-get-started": "Get Started",
		"hero-button-our-services": "Our Services",
		
		"about-title": "Your Partner in Global Trade",
		"about-description": "Zaivod Logistics is a transport company specializing in the transportation of a wide range of goods throughout the EU and Asia. With our extensive network and expert knowledge, we offer reliable, flexible, and cost-effective solutions that help our customers achieve their goals and grow their business.",
		"find-title": "Where can you find us?",
		"find-description": "We are located in the beautiful village of Voevodinovo. Here you can find our base.",
		"services-title": "Our Services",
		"services-subtitle": "Comprehensive logistics solutions for your business needs",
		"services-transport-title": "Cargo Transport", 
		"services-transport-description": "Reliable transportation of goods across EU and Asia with real-time tracking and secure delivery.",
		"services-cars-title": "Vehicle Trading",
		"services-cars-description": "Quality trucks and cars for sale with full documentation and international delivery.",
		"services-contact-us": "Contact Us",
		"contacts-title": "Contact Us",
		"contacts-description": "We would like to answer all questions related to our future work together. You can write to us at <b>zaidsadeqhi@gmail.com</b> or use the form below.",
		"contacts-company": "Company Name",
		"contacts-first-name": "First Name",
		"contacts-last-name": "Last Name",
		"contacts-email": "Email",
		"contacts-phone": "Phone",
		"contacts-message": "Message",
		"contacts-submit": "Send",
		"stats-years-experience": "Years Experience",
		"stats-happy-clients": "Happy Clients",
		"stats-countries-served": "Countries Served",
		"stats-on-time-delivery": "On-time Delivery",
	},
	"ps": {
		"head-description": "زود لوژستیک، په نړیواله سوداګرۍ کې ستاسو باوري ملګری.",
		"title": "زېووډ لوژستیکس",
		"hero-title": "نړیوالې لوژستیکي حل چې ستاسې بریالی کوي",
		"hero-description": "ستاسې په نړیوال ګرځیدلو او د موټرو په سوداګرۍ کې د باور وړ شریک. له ۲۰۱۰ څخه راپدېخوا په ټولو لویو وچو کې غوره والی رسول.",
		"hero-button-get-started": "پیل کړئ",
		"hero-button-our-services": "زموږ خدمتونه",
		
		"about-title": "ستاسو شریک په نړیواله سوداګرۍ کې",
		"about-description": "زېووډ لوژستیکس یوه د بار لېږд شرکت دی چې په اروپايي اتحادیه او آسیا کې د مختلفو توکو د لېږد تخصص لري. زموږ د پراخې شبکې او مسلکي پوهې سره، موږ د باور وړ، انعطاف وړ او اقتصادي حل لارې وړاندې کوو چې زموږ پیرودونکو ته مرسته کوي خپل هدفونه ترلاسه کړي او خپل سوداګرۍ وده کړي.",
		"find-title": "چېرې موږ پیدا کولی شئ؟",
		"find-description": "موږ د وووډینوو په ښایسته کلی کې موقعیت لرو. دلته تاسو کولی شئ زموږ اډه ومومئ.",
		"services-title": "زموږ خدمتونه",
		"services-subtitle": "د ستاسو د سوداګریزې اړتیاو لپاره بشپړې لوژستیکي حل لارې",
		"services-transport-title": "د بار لېږد",
		"services-transport-description": "د اروپا او آسیا په ټولو برخو کې د باور وړ د بار لېږد د رېال وخت تعقیب او خوندي رسول سره.",
		"services-cars-title": "د موټرو سوداګري", 
		"services-cars-description": "د بشپړې اسناد او نړیوالې رسولې سره کیفیتي ټرالرې او موټرې د پلور لپاره.",
		"services-contact-us": "موږ سره اړیکه ونیسئ",
		"contacts-title": "موږ سره اړیکه ونیسئ",
		"contacts-description": "موږ غواړو د زموږ د راتلونکي کار یوځای په اړه ټولې پوښتنې ته ځواب ووایو. تاسو کولی شئ زموږ ته په <b>zaidsadeqhi@gmail.com</b> برېښنالیک ولیکئ یا لاندې فورم وکاروئ.",
		"contacts-company": "د شرکت نوم",
		"contacts-first-name": "لومړی نوم",
		"contacts-last-name": "وروستی نوم",
		"contacts-email": "برېښنالیک",
		"contacts-phone": "تلیفون",
		"contacts-message": "پیغام",
		"contacts-submit": "ولېږئ",
		"stats-years-experience": "د تجربې کلونه",
		"stats-happy-clients": "خوښ پیرودونکی",
		"stats-countries-served": "خدمت شوي هېوادونه",
		"stats-on-time-delivery": "په وخت رسول",
	},
}
